// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ali Shaikh

package flociazcompat

import (
	"fmt"
	"sort"
	"strings"
)

// ProviderOverrideHCL returns the Terraform provider override for local floci-az.
func ProviderOverrideHCL(metadataHost string) string {
	metadataHost = strings.TrimSpace(metadataHost)
	return fmt.Sprintf(`# Generated by CloudSprocket from the floci-az OpenTofu compatibility contract.
# Source: floci-io/floci-az compatibility-tests/compat-opentofu
# Do not edit; recreated on every plan/apply/destroy.
provider "azurerm" {
  features {}

  subscription_id = %q
  client_id       = %q
  client_secret   = %q
  tenant_id       = %q

  metadata_host = %q

  resource_provider_registrations = "none"
  use_cli                         = false
}
`, SubscriptionID, ClientID, ClientSecret, TenantID, metadataHost)
}

// TofuEnvironment returns process environment entries for OpenTofu against floci-az.
func TofuEnvironment(runtime PreparedRuntime, extra map[string]string) []string {
	vars := map[string]string{
		"ARM_SUBSCRIPTION_ID": SubscriptionID,
		"ARM_CLIENT_ID":       ClientID,
		"ARM_CLIENT_SECRET":   ClientSecret,
		"ARM_TENANT_ID":       TenantID,
		"ARM_METADATA_HOSTNAME": runtime.MetadataHost,
		"ARM_USE_CLI":         "false",
		"SSL_CERT_FILE":       runtime.TrustCertPath,
	}
	for key, value := range extra {
		key = strings.TrimSpace(key)
		if key == "" || isProtectedTofuEnvKey(key) {
			continue
		}
		if strings.HasPrefix(key, "ARM_") || strings.HasPrefix(key, "AZURE_") {
			vars[key] = value
		}
	}
	return sortedEnv(vars)
}

func isProtectedTofuEnvKey(key string) bool {
	switch key {
	case "ARM_SUBSCRIPTION_ID", "ARM_CLIENT_ID", "ARM_CLIENT_SECRET", "ARM_TENANT_ID",
		"ARM_METADATA_HOSTNAME", "ARM_USE_CLI", "ARM_RESOURCE_MANAGER_ENDPOINT", "SSL_CERT_FILE":
		return true
	default:
		return false
	}
}

func sortedEnv(vars map[string]string) []string {
	keys := make([]string, 0, len(vars))
	for key := range vars {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	out := make([]string, 0, len(keys))
	for _, key := range keys {
		out = append(out, key+"="+vars[key])
	}
	return out
}