package deploy

import (
	"fmt"
	"sort"
	"strings"
)

// localStackServices are the AWS provider endpoint keys redirected to the
// emulator. The set covers the bundled recipe plus common free-tier services so
// other recipes work without editing this list.
var localStackServices = []string{
	"apigateway", "apigatewayv2", "cloudformation", "cloudfront", "cloudwatch",
	"dynamodb", "ec2", "ecr", "ecs", "elbv2", "events", "iam", "kinesis", "kms",
	"lambda", "logs", "rds", "route53", "s3", "secretsmanager", "sns", "sqs",
	"ssm", "sts",
}

// localStackOverride returns a Terraform override file that points the aws
// provider at the LocalStack endpoint with dummy credentials and path-style S3.
// This is the same redirection LocalStack's own `tflocal` wrapper performs, so
// a cloud-targeted recipe runs unchanged against the emulator.
func localStackOverride(endpoint string) string {
	services := append([]string(nil), localStackServices...)
	sort.Strings(services)

	var endpoints strings.Builder
	for _, service := range services {
		endpoints.WriteString(fmt.Sprintf("    %-15s = %q\n", service, endpoint))
	}

	return fmt.Sprintf(`# Generated by CloudSprocket: redirect the AWS provider to LocalStack.
# Do not edit; this file is recreated on every local deployment.
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
%s  }
}
`, endpoints.String())
}
