// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ali Shaikh

package deploy

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"cloudsprocket/backend/daemon/internal/config"
)

const (
	localAzureProfileName    = "cloudsprocket-floci-az"
	localFlociSubscriptionID = "00000000-0000-0000-0000-000000000001"
	defaultFlociAzEndpoint   = "http://localhost:4577"
	flociAzOverrideFile      = "cloudsprocket_floci_az_override.tf"
)

type flociAzTarget struct {
	endpoint string
}

func newFlociAzTarget(opts TargetOptions) *flociAzTarget {
	endpoint := strings.TrimSpace(opts.FlociAzEndpoint)
	if endpoint == "" {
		endpoint = defaultFlociAzEndpoint
	}
	return &flociAzTarget{endpoint: endpoint}
}

func (t *flociAzTarget) ID() string { return "floci-az" }

func (t *flociAzTarget) Label(_ *Deployment) string { return "floci-az" }

func (t *flociAzTarget) Env(_ *Deployment, settings config.Settings) []string {
	endpoint := strings.TrimRight(t.endpoint, "/")
	env := []string{
		"ARM_SUBSCRIPTION_ID=" + localFlociSubscriptionID,
		"ARM_CLIENT_ID=00000000-0000-0000-0000-000000000000",
		"ARM_CLIENT_SECRET=floci-az-local",
		"ARM_TENANT_ID=00000000-0000-0000-0000-000000000000",
		"ARM_RESOURCE_MANAGER_ENDPOINT=" + endpoint,
		"ARM_USE_CLI=false",
	}
	if path := flociAzEnvPath(settings); path != "" {
		if data, err := os.ReadFile(path); err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if line == "" || strings.HasPrefix(line, "#") {
					continue
				}
				key, _, ok := strings.Cut(line, "=")
				if !ok {
					continue
				}
				key = strings.TrimSpace(key)
				if strings.HasPrefix(key, "ARM_") || strings.HasPrefix(key, "AZURE_") {
					env = append(env, line)
				}
			}
		}
	}
	return env
}

func (t *flociAzTarget) Preflight(ctx context.Context, _ *Deployment, _ config.Settings, opts TargetOptions) error {
	endpoint := t.endpoint
	if strings.TrimSpace(endpoint) == "" {
		endpoint = opts.FlociAzEndpoint
	}
	if strings.TrimSpace(endpoint) == "" {
		endpoint = defaultFlociAzEndpoint
	}
	return checkFlociAzHealth(ctx, endpoint)
}

func (t *flociAzTarget) WriteOverrides(dir string, _ *Deployment, opts TargetOptions) error {
	endpoint := t.endpoint
	if strings.TrimSpace(endpoint) == "" {
		endpoint = opts.FlociAzEndpoint
	}
	if strings.TrimSpace(endpoint) == "" {
		endpoint = defaultFlociAzEndpoint
	}
	content := flociAzOverride(endpoint)
	return os.WriteFile(filepath.Join(dir, flociAzOverrideFile), []byte(content), 0o644)
}

func checkFlociAzHealth(ctx context.Context, endpoint string) error {
	base := strings.TrimRight(endpoint, "/")
	probeCtx, cancel := context.WithTimeout(ctx, preflightTimeout)
	defer cancel()

	request, err := http.NewRequestWithContext(probeCtx, http.MethodGet, base+"/", nil)
	if err != nil {
		return err
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return fmt.Errorf("floci-az is not reachable at %s. Start it from Local Runtime, then try again", endpoint)
	}
	defer response.Body.Close()
	if response.StatusCode < 200 || response.StatusCode >= 500 {
		return fmt.Errorf("floci-az at %s is not ready (HTTP %d). Wait for it to finish starting, then try again", endpoint, response.StatusCode)
	}
	return nil
}

func flociAzEnvPath(settings config.Settings) string {
	if dir := strings.TrimSpace(settings.LocalConfigDir); dir != "" {
		return filepath.Join(dir, "azure", "floci-az.env")
	}
	return ""
}

func isLocalFlociProfileID(profileID string) bool {
	return strings.TrimSpace(profileID) == localAzureProfileName
}

// flociAzOverride returns a Terraform override that points the azurerm provider
// at the local floci-az emulator instead of real Azure.
func flociAzOverride(endpoint string) string {
	endpoint = strings.TrimRight(strings.TrimSpace(endpoint), "/")
	return fmt.Sprintf(`# Generated by CloudSprocket: redirect the azurerm provider to floci-az.
# Do not edit; this file is recreated on every local Azure deployment.
provider "azurerm" {
  features {}

  subscription_id = %q
  client_id       = "00000000-0000-0000-0000-000000000000"
  client_secret   = "floci-az-local"
  tenant_id       = "00000000-0000-0000-0000-000000000000"

  resource_provider_registrations = "none"
  use_cli                         = false
}
`, localFlociSubscriptionID)
}