package deploy

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cloudsprocket/backend/daemon/internal/config"
)

// localStackServices are the AWS provider endpoint keys redirected to the
// emulator. The set covers the bundled recipe plus common free-tier services so
// other recipes work without editing this list.
var localStackServices = []string{
	"apigateway", "apigatewayv2", "cloudformation", "cloudfront", "cloudwatch",
	"dynamodb", "ec2", "ecr", "ecs", "elbv2", "events", "iam", "kinesis", "kms",
	"lambda", "logs", "rds", "route53", "s3", "secretsmanager", "sns", "sqs",
	"ssm", "sts",
}

type localStackTarget struct {
	endpoint string
}

func (t *localStackTarget) ID() string { return "localstack" }

func (t *localStackTarget) Label(_ *Deployment) string { return "LocalStack" }

func (t *localStackTarget) Env(_ *Deployment, _ config.Settings) []string {
	return []string{
		"AWS_ACCESS_KEY_ID=test",
		"AWS_SECRET_ACCESS_KEY=test",
		"AWS_DEFAULT_REGION=us-east-1",
	}
}

func (t *localStackTarget) Preflight(ctx context.Context, _ *Deployment, _ config.Settings, opts TargetOptions) error {
	endpoint := t.endpoint
	if strings.TrimSpace(endpoint) == "" {
		endpoint = opts.LocalStackEndpoint
	}
	if strings.TrimSpace(endpoint) == "" {
		endpoint = DefaultLocalStackEndpoint
	}
	return checkLocalStackHealth(ctx, endpoint)
}

func (t *localStackTarget) WriteOverrides(dir string, _ *Deployment, opts TargetOptions) error {
	endpoint := t.endpoint
	if strings.TrimSpace(endpoint) == "" {
		endpoint = opts.LocalStackEndpoint
	}
	if strings.TrimSpace(endpoint) == "" {
		endpoint = DefaultLocalStackEndpoint
	}
	content := localStackOverride(endpoint)
	return os.WriteFile(filepath.Join(dir, overrideFile), []byte(content), 0o644)
}

func checkLocalStackHealth(ctx context.Context, endpoint string) error {
	base := strings.TrimRight(endpoint, "/")
	probeCtx, cancel := context.WithTimeout(ctx, preflightTimeout)
	defer cancel()

	request, err := http.NewRequestWithContext(probeCtx, http.MethodGet, base+"/_localstack/health", nil)
	if err != nil {
		return err
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return fmt.Errorf("LocalStack is not reachable at %s. Start it from Local Runtime, then try again", endpoint)
	}
	defer response.Body.Close()
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return fmt.Errorf("LocalStack at %s is not ready (HTTP %d). Wait for it to finish starting, then try again", endpoint, response.StatusCode)
	}
	return nil
}

// localStackOverride returns a Terraform override file that points the aws
// provider at the LocalStack endpoint with dummy credentials and path-style S3.
func localStackOverride(endpoint string) string {
	services := append([]string(nil), localStackServices...)
	sort.Strings(services)

	var endpoints strings.Builder
	for _, service := range services {
		endpoints.WriteString(fmt.Sprintf("    %-15s = %q\n", service, endpoint))
	}

	return fmt.Sprintf(`# Generated by CloudSprocket: redirect the AWS provider to LocalStack.
# Do not edit; this file is recreated on every local deployment.
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
%s  }
}
`, endpoints.String())
}